project:
  type: website
  output-dir: docs

website:
  title: "Avner A. Kreps"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: files/cv.pdf
        text: CV
  search: false

format:
  html:
    theme: 
      - simplex
      - more-styles.scss
    css: styles.css
    toc: false
    callout-icon: false
    callout-appearance: minimal
    page-layout: full
    email-obfuscation: javascript

editor: visual

resources:
  - CNAME

