project:
  type: website
  output-dir: docs

website:
  title: "Avner A. Kreps"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - href: files/cv.pdf
        text: CV
  search: false

format:
  html:
    theme: 
      - pulse
      - mre-styles.scss
    css: styles.css
    toc: false
    callout-icon: false
    callout-appearance: minimal
    page-layout: full

editor: visual

resources:
  - CNAME

