---
pagetitle: Avner A. Kreps - Research
---

## Working papers

| [**Information Sharing and Collusion: Theory and Evidence from Poultry Processing**](files/jmp.pdf){target="_blank"}
| *Job market paper*

```{=html}
  <button class="btn-sm" type="button" data-bs-toggle="collapse" data-bs-target="#a-poultry" aria-expanded="false" aria-controls="a-poultry">
            Abstract
  </button>

<div class="collapse gap-1" id="a-poultry">
  <div class="card card-body">
    Information exchanges among competitors have become more prevalent in recent years. While they may facilitate collusion, they may also affect outcomes purely by informing firms about their economic environment. Empirically distinguishing between these two forces is crucial for conduct testing and policy evaluation. This paper develops tools to do so and applies them to the Agri Stats information exchange among turkey processors. In the year after the exchange broke down, the retail price of participating processors fell by 5.1% relative to other processors, and descriptive evidence is suggestive of both conduct and information effects. I specify and estimate a structural model that identifies changes to conduct while controlling for information effects. I reject the null hypothesis of no conduct change, and estimate that subscribers acted like they internalized 47% of other participants’ profits while sharing information. Information effects of the exchange alone reduce prices by 1.3%, but are outweighed by conduct effects. Bounds on collusive prices under counterfactual restrictions on information sharing indicate that firms can still attain near-monopoly profits even when sharing aggregated information.
  </div>
</div>
```

|
| [**Firm Productivity and Learning with Digital Technologies: Evidence from Cloud Computing**](files/cloud_productivity.pdf){target="_blank"}
| with [James Brand](https://www.jamesbrandecon.com), [Mert Demirer](https://www.mertdemirer.com/), and Connor Finucane

```{=html}
  <button class="btn-sm" type="button" data-bs-toggle="collapse" data-bs-target="#a-cloud-prod" aria-expanded="false" aria-controls="a-cloud-prod">
            Abstract
  </button>

<div class="collapse gap-1" id="a-cloud-prod">
  <div class="card card-body">
    Digital technologies have transformed firm production across all sectors. In this paper, we document new facts about firms’ productivity with emerging technologies by studying how efficiently they use cloud computing. Leveraging high-frequency CPU utilization data from nearly 100,000 firms, we find large and persistent dispersion in firms' cloud productivity. Productivity, however, is highly dynamic in this setting: firms improve their cloud productivity by 33% in the first year after adoption, and reach a stable level only after four years, indicating a long adjustment period to learn the technology. While faster learning among initially less efficient firms reduces productivity dispersion by 60% over time, substantial heterogeneity remains even after 10 years. Finally, productivity improvements occur primarily within individual divisions of a firm, with minimal knowledge transfer across divisions.
  </div>
</div>
```

|
| [**A Large-Scale Evaluation of Merger Simulations**](files/merger_sim.pdf){target="_blank"}
| with [Vivek Bhattacharya](https://sites.northwestern.edu/vivek), [Gastón Illanes](https://sites.northwestern.edu/gil208), José D. Salas, and [David Stillerman](https://sites.google.com/view/davidstillerman)
| *Revise and resubmit, American Economic Review*

```{=html}
  <button class="btn-sm" type="button" data-bs-toggle="collapse" data-bs-target="#a-merger_sim" aria-expanded="false" aria-controls="a-merger_sim">
            Abstract
  </button>

<div class="collapse gap-1" id="a-merger_sim">
  <div class="card card-body">
    Prospective merger simulations are a commonly used tool in industrial organization and antitrust, but evidence about their accuracy and predictive ability is limited. We study 101 mergers in consumer packaged goods and compare the realizations of price changes with predictions from merger simulations. In our sample of consummated mergers, predicted price changes from merger simulations are typically larger than realized ones. Despite the overprediction, we find that full merger simulations are more effective than both structural presumptions and approximations of the merger effect at identifying mergers with large price changes.
  </div>
</div>
```

## Publications

| [**Rules for the Rulemakers: Asymmetric Information and the Political Economy of Benefit-Cost Analysis**](https://link.springer.com/article/10.1007/s11149-024-09483-4){target="_blank"}
| with [David Besanko](https://www.kellogg.northwestern.edu/faculty/directory/besanko_david.aspx) and [Clair Yang](https://sites.google.com/site/clairzyang/home)
| *Journal of Regulatory Economics* 66(1):1--51, 2024

```{=html}
  <button class="btn-sm" type="button" data-bs-toggle="collapse" data-bs-target="#a-rules" aria-expanded="false" aria-controls="a-rules">
            Abstract
  </button> <a href="files/bca_online_appendix.pdf"><button class="btn-sm" type="button">
            Online Appendix
  </button> </a>

<div class="collapse gap-1" id="a-rules">
  <div class="card card-body">
    This paper presents a model of an executive administration that decides whether to mandate benefit-cost analysis (BCA) of newly proposed regulations. A regulator has private information about the social benefit of a new rule but may differ from the executive’s preferences for regulation. BCA, which provides a noisy signal of the rule’s social benefit, is most valuable when the executive is regulation neutral. Extremely regulation-averse administrations may be harmed by BCA unless they can bias it. Our results are consistent with use of BCA by U.S. presidential administrations since Reagan.
  </div>
</div>
```

## Works in progress

| **Antitrust Spillovers: Evidence from Meatpacking, 1917–1921**
